name: test CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: test deploy
      uses: appleboy/jenkins-action@master
      with:
        url: ""
        user: "g9736ms"
        token: {{test}}
        job: "anthony test"
